### ISSUE TITLE
How to run server using specific ip and port

### ISSUE THREAD

**Issue by hugochan** [dinever/crotal#17]
Could you please add it into the document?

**Comment by dinever** [comment]
Hi,

Sorry for the incomplete information of the document.

To run server using specific port, you can use `-p` argument:

For example, run server on port `8080`:

```
crotal server -p 8080
```

The ip of the server is based on the ip address of your machine running the server.

Thank you!

**Comment by hugochan** [comment]
Hi Peixuan,

I wanted to deploy the site on a remote machine. Do I need to config anything? I wanted but failed to specify the ip when running server. The default ip is localhost. Any help will be greatly appreciated!

Thank you,
Yu

**Comment by dinever** [comment]
Hi,

There are so many ways to deploy a static website. The whole website files are in the `preview` folder, and how to deploy it is based on your remote machine:

- If you have other servers like `nginx` or `apache` installed on the remote machine. The simplest way is to put everything inside the folder `preview` to your remote machine's server directory. 

- If you don't have any servers like `nginx` or `apache` installed on the remote machine. You can put the whole crotal site folder to the remote machine and install & run crotal server on the remote machine.

Let me know if you have any other questions. 

Thank you

**Comment by hugochan** [comment]
Thanks! The problem is solved. Thanks again for your great job!
